### ISSUE TITLE
The positive viral sequence was filtered out during the construction of tree

### ISSUE THREAD

**Issue by franco-ye** [ZiyueYang01/VirID#11]
Hello Developer:
    Thanks to the development of the all-in-one tool for detecting RNA viruses, I encountered errors while running the code.
1. [WARNING: Picorna-Calici:1 records contigs that do not reach the threshold]
2. [ERROR: An error was encountered while running mafft in result/phylogenetic_analysis/Picorna-Calici/Picorna-Cali]

    The program is functioning well. I am wondering why a known RNA sequence is excluded when building an evolutionary tree.

**Comment by ZiyueYang01** [comment]
1.  To accelerate the analysis of the Picorna-Calici superclade, we excluded contigs encoding proteins with fewer than 400 amino acids before alignment, as detailed in VirID/config/config.py.
2. This error may be due to mafft didn't run successfully, you can email me the sequence `yangzy58@mail2.sysu.edu.cn` and I'll test.

**Comment by franco-ye** [comment]
Thank you for your reply. The data I tested is a known virus sequence. I will email it to you. Thank you for your assistance!
